### ISSUE TITLE
貌似给XmanagerPowerSuite-6.0.0030r的序列号是无效的

### ISSUE THREAD

**Issue by cottonthread** [bajins/tool-gin#1]
感谢你的程序，但是看起来用于XmanagerPowerSuite-6.0.0030r的序列号是无效的，我尝试算了好几次都不行：
![image](https://user-images.githubusercontent.com/62510349/91556636-582a6a00-e933-11ea-9d7c-74bd7c13aeb3.png)
![image](https://user-images.githubusercontent.com/62510349/91556601-4ba61180-e933-11ea-926a-bf32508be027.png)

给XshellPlus-6.0.0030r计算的序列号是OK哒~

**Comment by bajins** [comment]
目前最新版本的支持是有问题的，因为官方的认证方式会有变化，当前key的计算已经很久没更新了，可以试试 https://gd.bajins.com/DeveloperTool/SSH/NetSarang_AIO_8in1_Keygen_v1.6_DFoX_%E5%AF%86%E7%A0%81bajins.zip

**Comment by cottonthread** [comment]
> 目前最新版本的支持是有问题的，因为官方的认证方式会有变化，当前key的计算已经很久没更新了，可以试试 https://gd.bajins.com/DeveloperTool/SSH/NetSarang_AIO_8in1_Keygen_v1.6_DFoX_%E5%AF%86%E7%A0%81bajins.zip

收到，谢谢！
