### ISSUE TITLE
获取key提示系统错误！

### ISSUE THREAD

**Issue by qxwo** [bajins/tool-gin#6]
![微信图片_20210520125317](https://user-images.githubusercontent.com/23393355/118921229-61001780-b96a-11eb-890b-d985fdc607c8.png)

**Comment by qxwo** [comment]
换debian10 可以获取key了，但是激活失败了
[Reason: 8417] The product key is not valid. Please check your product key and try again.

**Comment by bajins** [comment]
key 只适合6版本
